"""Third migration

Revision ID: 15a6b30950d9
Revises: f760b12b3c18
Create Date: 2023-12-15 14:53:36.342657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a6b30950d9'
down_revision = 'f760b12b3c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idPrivateUser', sa.Integer(), nullable=True))
        batch_op.drop_constraint('category_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint('category_name_key', ['name'])
        batch_op.drop_column('idPrivateUser')

    # ### end Alembic commands ###
